In [2]:
#1

import pandas as pd 
# read the csv file
df = pd.read_csv("/Users/bosslistic10/Documents/t-programming/rna_weight.csv", sep = ",", index_col = 0)
# display to see content of file
display(df)

s = "AUGGCUAACUGG"
# initialize variable to add 
fw = 0
# loop through s, locate mw, the add into fw
for i in s:
    fw += df.loc[i, "MolecularWeight"]
# substract 18 from the total no of bonds  
fw -= 18 * (len(s) - 1)
# print the result
print(f"Molecular weight of RNA: {fw:.1f} g/mol")

            MolecularWeight
Nucleotide
A                     347.2
U                     324.2
G                     363.2
C                     323.2

Molecular weight of RNA: 3915.4 g/mol

In [3]:
#2
# read the csv file
df1 = pd.read_csv("/Users/bosslistic10/Documents/t-programming/Python/Practice docs/amino_weights.csv", sep = ",", index_col = 0)

display(df1)

# protein seq and initalize weight to zero
ps = "MVKGL"
w = 0

# loop through ps, add to weight by location
for i in ps:
    w += df1.loc[i] ["MolecularWeight"]
# substract 18 from the no of bonds
w -= 18 * (len(ps) - 1)

# print the result
print(f"Molecular weight of peptide: {w} g/mol")

           MolecularWeight
AminoAcid
M                    149.2
V                    117.1
K                    146.2
G                     75.1
L                    131.2

Molecular weight of peptide: 546.8 g/mol

In [4]:
df2 = pd.read_csv("/Users/bosslistic10/Documents/t-programming/rna_weight.csv", sep = ",", index_col = 0)
# display to see content of file
display(df2)

s = "AUGGCUAACUGX"
# initialize variable to add 
fw = 0
# loop through s, locate mw, the add into fw
for i in s:
    if i in df.index:
        fw += df2.loc[i, "MolecularWeight"]
    elif i not in df.index:
        print("Unknown nucleotide:  X")
        print("Calculation would continue below\n")
# substract 18 from the total no of bonds  
fw -= 18 * (len(s) - 1)
# print the result
print(f"Molecular weight of RNA: {s} is {fw:.1f} g/mol")

            MolecularWeight
Nucleotide
A                     347.2
U                     324.2
G                     363.2
C                     323.2

Unknown nucleotide:  X
Calculation would continue below

Molecular weight of RNA: AUGGCUAACUGX is 3552.2 g/mol

In [27]:
# 3 from prog exam 

df3 = pd.read_csv("/Users/bosslistic10/Documents/t-programming/Python/School docs/mock_exam/mock 2/dataframe.csv.txt", sep = "\t", index_col = 0)

display(df3)

s = "ATGGTGGAACTA"
b2aa = ""
for i in range(0, len(s)-2, 3):

    cut = s[i:i+3]

    match = df3.loc[cut, "Amino acid"]

    b2aa += match
    
print(f"The matching amino acids to from the {s} is {b2aa}")

    Base 1 Base 2 Base 3 Amino acid
CCC      C      C      C          P
ACC      A      C      C          T
GCC      G      C      C          A
CCA      C      C      A          P
ACA      A      C      A          T
..     ...    ...    ...        ...
AGT      A      G      T          S
GGT      G      G      T          G
TGC      T      G      C          C
TGA      T      G      A          *
TGG      T      G      G          W

[64 rows x 4 columns]

The matching amino acids to from the ATGGTGGAACTA is MVEL